name = mobs
description = Adds a mob api for mods to add animals or monsters etc.
optional_depends = default, tnt, invisibility, cmi, toolranks, pathfinder, visual_harm_1ndicators, mcl_core
min_minetest_version = 5.0
title = Mobs Redo API
release = 31633
author = TenPlus1
