--[[
Map Tools: alias definitions

Copyright © 2012-2019 Hugo Locurcio and contributors.
Licensed under the zlib license. See LICENSE.md for more information.
--]]

core.register_alias("adminpick", "maptools:pick_admin")
core.register_alias("adminpickaxe", "maptools:pick_admin")
core.register_alias("admin_pick", "maptools:pick_admin")
core.register_alias("admin_pickaxe", "maptools:pick_admin")
core.register_alias("pick_admin", "maptools:pick_admin")
core.register_alias("pickaxe_admin", "maptools:pick_admin")
core.register_alias("pickadmin", "maptools:pick_admin")
core.register_alias("pickaxeadmin", "maptools:pick_admin")
core.register_alias("infinitefuel", "maptools:infinitefuel")
core.register_alias("infinite_fuel", "maptools:infinitefuel")
core.register_alias("ifuel", "maptools:infinitefuel")
core.register_alias("superapple", "maptools:superapple")
core.register_alias("super_apple", "maptools:superapple")
core.register_alias("sapple", "maptools:superapple")
core.register_alias("nobuild", "maptools:nobuild")
core.register_alias("nointeract", "maptools:nointeract")
core.register_alias("damage_1", "maptools:damage_1")
core.register_alias("damage_2", "maptools:damage_2")
core.register_alias("damage_3", "maptools:damage_3")
core.register_alias("damage_4", "maptools:damage_4")
core.register_alias("damage_5", "maptools:damage_5")
core.register_alias("pusher_1", "maptools:pusher_1")
core.register_alias("pusher_2", "maptools:pusher_2")
core.register_alias("pusher_3", "maptools:pusher_3")
core.register_alias("pusher_4", "maptools:pusher_4")
core.register_alias("pusher_5", "maptools:pusher_5")
core.register_alias("pusher_6", "maptools:pusher_6")
core.register_alias("pusher_7", "maptools:pusher_7")
core.register_alias("pusher_8", "maptools:pusher_8")
core.register_alias("pusher_9", "maptools:pusher_9")
core.register_alias("pusher_10", "maptools:pusher_10")
core.register_alias("killblock", "maptools:kill")
core.register_alias("kill_block", "maptools:kill")
core.register_alias("lightblock", "maptools:lightblock")
core.register_alias("light_block", "maptools:lightblock")
core.register_alias("lightbulb", "maptools:lightbulb")
core.register_alias("light_bulb", "maptools:lightbulb")
core.register_alias("playerclip", "maptools:playerclip")
core.register_alias("player_clip", "maptools:playerclip")
core.register_alias("pclip", "maptools:playerclip")
core.register_alias("fullclip", "maptools:fullclip")
core.register_alias("full_clip", "maptools:fullclip")
core.register_alias("fclip", "maptools:fullclip")
core.register_alias("full_clip", "maptools:fullclip")
core.register_alias("full_clip_face", "maptools:fullclip_face")
core.register_alias("fullclip_face", "maptools:fullclip_face")
core.register_alias("fullclipface", "maptools:fullclip_face")
core.register_alias("player_clip_bottom", "maptools:playerclip_bottom")
core.register_alias("playerclip_bottom", "maptools:playerclip_bottom")
core.register_alias("playerclipbottom", "maptools:playerclip_bottom")
core.register_alias("player_clip_top", "maptools:playerclip_top")
core.register_alias("playerclip_top", "maptools:playerclip_top")
core.register_alias("playercliptop", "maptools:playerclip_top")
core.register_alias("permanentfire", "maptools:permanent_fire")
core.register_alias("permanent_fire", "maptools:permanent_fire")
core.register_alias("pfire", "maptools:permanent_fire")
core.register_alias("fakefire", "maptools:fake_fire")
core.register_alias("fake_fire", "maptools:fake_fire")
core.register_alias("ffire", "maptools:fake_fire")
core.register_alias("igniter", "maptools:igniter")
