name = item_details
depends = default
optional_depends = 3d_armor, armor_shadow, ctf_ranged, ffa_boss, ffa_loot, farming, flowers, maptools, skywars, throwables, xdecor
description = Adds consistent gameplay details to inventory items.
